version: "3.9"

services:
  nginx:
    image: nginx:1.27-alpine
    container_name: ${PROJECT_NAME}_nginx
    ports:
      - "${HOST_PORT}:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./docker/nginx/sites-available:/etc/nginx/sites-available
      - ./src:/var/www/html
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - php
    networks:
      - app

  php:
    build:
      context: .
      dockerfile: docker/php/${PHP_VERSION}/Dockerfile
    container_name: ${PROJECT_NAME}_php
    ports:
      - "${PHP_PORT}:9000"
    volumes:
      - ./src:/var/www/html
      - ./docker/php/${PHP_VERSION}/php.ini:/usr/local/etc/php/php.ini
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
    networks:
      - app

  node:
    image: node:${NODE_VERSION}
    container_name: ${PROJECT_NAME}_node
#    ports:
#      - "${NODE_PORT}:5173"
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    command: [ "tail", "-f", "/dev/null" ]
    networks:
      - app

  redis:
    image: redis:${REDIS_VERSION}
    container_name: ${PROJECT_NAME}_redis
    volumes:
      - ./data/redis:/data
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - app

networks:
  app:
