version: "3.9"

services:
  pgsql:
    image: postgres:${PGSQL_VERSION}
    container_name: ${PROJECT_NAME}_pgsql
    restart: unless-stopped
    ports:
      - "${PGSQL_PORT}:5432"
    volumes:
      - ./data/pgsql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PGSQL_PASSWORD}
      POSTGRES_USER: ${PGSQL_USER}
      POSTGRES_DB: ${PGSQL_DATABASE}
    networks:
      - app
